# name: Build Xamarin.Android app

# on: [push]

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Set default Xamarin SDK versions
#       run: |
#         $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=13.2.1.2

#     - name: Setup .NET Core SDK 7.0.x
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: '7.0.x'

#     - name: Install dependencies
#       run: nuget restore DemoCICD.sln

#     - name: Build
#       run: msbuild DemoCICD/DemoCICD.csproj /t:PackageForAndroid /p:Configuration=Debug


name: Build Apk

on: [push]

jobs:
  Android:
    name: Android
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bradyjoslin/xamarinandroid-signedbuild-action@v1
        with:
          csproj_path: DemoCICD/DemoCICD.csproj
          signing_keystore: DemoCICD/hoang.keystore
          keystore_password: 123123
          signing_key_alias: hoang
          signing_key_password: 123123
          configuration: "Release"
      - uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: DemoCICD/bin/Android/Release/AndroidReleaseSigned.apk